export const ResponseMessage = {
  MISSING_RESPONSE_BODY: "Response Body is missing.",
  UNAUTHORIZED_ACTION: "You are not authorized to perform this action.",
  INTERNAL_ERROR: "An unexpected error occurred.",
  EMAIL_PASSWORD_REQUIRED: "Email and Password are required.",
  REGISTRATION_SUCCESS: "User registered successfully.",
  USER_ALREADY_EXISTS: "User already exists",
  SSM_PARAMETER_NOT_FOUND: "SSM parameter not found.",
  INVALID_LOGIN_CREDIENTAL: "Invalid email or password.",
  LOGIN_USER_SUCCESS: "Login Successfully.",
  VALIDATION_FAILED: "Validation Failed.",
  CREATE_EVENT_SUCCESS: "Event created successfully!",
  MISSING_PATH_URL: "Missing required URL path parameter",
  CREATE_TICKET_TIER_SUCCESS:
    "Ticket tiers created successfully for this event.",
  NO_EVENT_FOUND: "Event not Found.",
  SUCCESS: "Success",
  INVALID_EVENT_ID: "No Event is associate with this event Id.",
  EMAIL_CLAIM_NOT_FOUND: "Email claim not found.",
  USER_NOT_FOUND: "User not Found.",
  MALFORMED_JSON_BODY: "Malformed JSON body syntax.",
  TICKET_TIER_NOT_FOUND: "No Ticket tier details exists for this event.",
  NO_BOOKING_FOUND: "No bookings found for this user.",
  CREATE_BOOKING_SUCCESS: "Booking created successfully.",
} as const;
